site_name: redispatcher
repo_url: https://github.com/rafalstapinski/redispatcher
repo_name: rafalstapinski/redispatcher
docs_dir: mkdocs
site_dir: docs

nav:
  - About: index.md
  - Contributing: contributing.md

theme:
  name: material
  favicon: img/favicon.png
  palette:
    primary: deep orange
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

