name: Test

on:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
      fail-fast: false

    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - name: Install redis-server
        run: |
          sudo apt-get update
          sudo apt-get install redis-server

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.12"

      - name: Install dependencies
        run: poetry install

      - run: which redis-server

      - name: Run pytest
        run: poetry run pytest test

      - name: Run isort
        run: poetry run isort --sp pyproject.toml --check .

      - name: Run black
        run: poetry run black --config pyproject.toml --check .

      - name: Run pylint
        run: poetry run pylint redispatcher/

      - name: Check package version
        run: poetry run python scripts/assert_package_versions_match.py
